---
title: "code.data.visualization"
author: "Yunyi Sun"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### library
```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(corrplot)
library(summarytools)
library(car)
library(GGally)
library(ggpubr)
```

#### Data Visulization
#### this is a example data set I used to demonstrated, you can change to yours


#### Histogram
```{r}

df <- read.csv("fifa_18_sample_data.csv")
View(df)

df1 <- df %>% select(age,height_cm,weight_kg,body_type,real_face)
df1 <- mutate_at(df1, vars(body_type,real_face), as.factor)
attach(df1)
levels(df1$body_type)

K = 1 + 3.322*log(length(df1))
  for (col in colnames(df1)){
    if (is.integer(df1[[col]])){
      x.name <- col
    for (col in colnames(df1)){
       if (is.factor(df1[[col]])){
      y.name <- col
  p <- gghistogram(df1, x = x.name,ylab=c("Frequency"),fill = y.name, bins =K,  add = "mean")+ ggtitle(paste("Histogram of ", x.name,sep="")) + theme(plot.title = element_text(hjust = 0.5))
  print(p)}  
      }
    }
  }
```


#### Boxplot
```{r}

# boxplot

for (col in colnames(df1)){
    if (is.factor(df1[[col]])){
      x.name <- col
    for (col in colnames(df1)){
       if (is.integer(df1[[col]])){
      y.name <- col
p <- ggboxplot(df1, x = x.name, y = y.name,  font.label = list(size = 6, color = "black") , width = 0.7, color = x.name)
print(p)
      }
       }
    }
}



```


#### Some correlation plots
```{r}
### correlation with statistical test
temp <- df1 %>% select(where(is.integer))
colnames(temp)
ggpairs(df1[, colnames(temp)])

```
